# Ruff configuration file
# https://docs.astral.sh/ty/configuration/

[environment]
root = ["./src"]
python-version = "3.12"

[src]
exclude = [
    "test_**",
    "tests",
]

[rules]
no-matching-overload = "ignore"